### ISSUE TITLE
CUDA out of memory in per-scene optimization

### ISSUE THREAD

**Issue by yangwangpku** [jetd1/NeRFusion#7]
Thanks for sharing the code.

However, when I run per-scene optimization,   CUDA is out of memory even if I set the batch size to 1.

The code is listed below:
```
CUDA_VISIBLE_DEVICES=2,3,4 python train.py --dataset_name scannet --root_dir scene0000_01 --exp_name exp --num_gpus 3 --batch_size 1,
```
and the output:
```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [2,3,4]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [2,3,4]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [2,3,4]

Training: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "train.py", line 259, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 223, in on_run_start
    self.trainer._call_lightning_module_hook("on_train_start")
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "train.py", line 146, in on_train_start
    self.model.prune_cells(self.train_dataset.K.to(self.device),
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yangwang/NeRFusion/models/nerfusion.py", line 191, in prune_cells
    uvd = K @ xyzs_c  # (N_cams, 3, chunk)
RuntimeError: CUDA out of memory. Tried to allocate 2.34 GiB (GPU 0; 10.76 GiB total capacity; 7.21 GiB already allocated; 1.23 GiB free; 7.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/yangwang/NeRFusion/train.py", line 259, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 223, in on_run_start
    self.trainer._call_lightning_module_hook("on_train_start")
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/yangwang/NeRFusion/train.py", line 146, in on_train_start
    self.model.prune_cells(self.train_dataset.K.to(self.device),
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yangwang/NeRFusion/models/nerfusion.py", line 191, in prune_cells
    uvd = K @ xyzs_c  # (N_cams, 3, chunk)
RuntimeError: CUDA out of memory. Tried to allocate 2.34 GiB (GPU 2; 10.76 GiB total capacity; 4.87 GiB already allocated; 263.56 MiB free; 4.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/yangwang/NeRFusion/train.py", line 259, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 223, in on_run_start
    self.trainer._call_lightning_module_hook("on_train_start")
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/yangwang/NeRFusion/train.py", line 146, in on_train_start
    self.model.prune_cells(self.train_dataset.K.to(self.device),
  File "/opt/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yangwang/NeRFusion/models/nerfusion.py", line 190, in prune_cells
    xyzs_c = w2c_R @ xyzs_w + w2c_T  # (N_cams, 3, chunk)
RuntimeError: CUDA out of memory. Tried to allocate 2.34 GiB (GPU 1; 10.76 GiB total capacity; 2.53 GiB already allocated; 1.98 GiB free; 2.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Environment:
GeForce RTX 2080 Ti
ubuntu 20.04
cuda 11.4
pytorch 1.12.1

If you have any idea about this problem, i will be really appreciated.

**Comment by jetd1** [comment]
Hi the code should be able to run with even one 2080 Ti. Could you test with 1 GPU and see if that passes? If so I will investigate into this multi-gpu related bug. Also could you test with `--downsample 0.5` to see if test passes.

**Comment by yangwangpku** [comment]
I test it with 1 GPU and it still fails. However, the code can run with one 3080 Ti.
